name: Sleep for 5 seconds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Sleep for 5 seconds
      run: sleep 5

